### ISSUE TITLE
The demo included does not work on Firefox 34.0.5

### ISSUE THREAD

**Issue by ketri** [anselmh/object-fit#17]
I downloaded the zip, and it seems like the polyfill doesn't get activated for Firefox.
![screenshot 2014-12-17 12 21 22](https://cloud.githubusercontent.com/assets/2366950/5469704/79d9ed70-85e7-11e4-95ce-66eab183811a.png)

**Comment by anselmh** [comment]
Closing this now as initial bug isn’t reproducible and IE bug has its own issue.
