### ISSUE TITLE
CORS advice is bogus

### ISSUE THREAD

**Issue by annevk** [anselmh/object-fit#25]
There's some CORS advice in the README.md that suggests "use-credentials" would work with *, but it won't. If you include credentials the server needs to reply with two headers, one of which includes the origin on question.

**Comment by annevk** [comment]
You probably still want to point out the attribute. It's rather important as the fetcher indicates what type of CORS the server needs to reply with.

**Comment by anselmh** [comment]
Thanks for reporting and the additional information, Anne. Is it fine now? :)

**Comment by annevk** [comment]
Not really. The pairing is `crossorigin=""` with `Access-Control-Allow-Origin: *` and `crossorigin="use-credentials"` with `Access-Control-Allow-Origin: [origin]` + `Access-Control-Allow-Credentials: true`. I suspect you almost never need the latter for CSS.

**Comment by anselmh** [comment]
Now I’m confused. Isn’t that what I had before except I had the `crossorigin="use-credentials"` paired with `*`? So is it correct to state this?

>Set header to: 
`'Access-Control-Allow-Origin: *'`
And on the CSS link:
`crossorigin=""`

**Comment by annevk** [comment]
I assumed you had a reason to advice `"use-credentials"`.
