### ISSUE TITLE
Firefox 17.0.6 script not responding

### ISSUE THREAD

**Issue by dmail** [anselmh/object-fit#28]
Firefox 17.0.6 displays a popup indicating the script `polyfill.object-fit.min.js:1` is not responding.

I'll try to get more information about this and keep you informed.

**Comment by anselmh** [comment]
Oh wow, what’s the case for using such an old, outdated Firefox version? How many images have you applied the polyfill on?

**Comment by dmail** [comment]
One of our customer uses this firefox version for testing purpose.
I've used this polyfill on one <video> with `object-fit: cover`, no more.

**Comment by anselmh** [comment]
@dmail hey, I cannot reproduce this on a Mac and the current version from `master` (not the latest published version) of this polyfill. Can you test this with the master source again by any chance? I’ll probably release a bugfix version soon.

**Comment by anselmh** [comment]
I’m closing this now as not reproducible.
