### ISSUE TITLE
Use external polyfills

### ISSUE THREAD

**Issue by TrySound** [anselmh/object-fit#30]
You can use external polyfill of [requestAnimationFrame](https://github.com/ngryman/raf.js/blob/master/raf.js). It's a little smaller. And dependencies let the code be smaller.

**Comment by TrySound** [comment]
[closest](https://github.com/jonathantneal/closest) is good for `elements.matches`.

**Comment by TrySound** [comment]
For "copy-lib" you may build bundle. For package managers build just core file and maybe getMatchedCSSRules polyfill. Other polyfills will be loaded as dependencies.

**Comment by TrySound** [comment]
Using `closest` will a little increase performance.

**Comment by anselmh** [comment]
Hi, thanks for the suggestions. I agree this could be done and have replaced the rAF polyfill with the one from npm.

I’ll see if I can make use of the closest polyfill and if it makes sense to use it here. Thanks for the hint.

> For "copy-lib" you may build bundle. For package managers build just core file and maybe getMatchedCSSRules polyfill. Other polyfills will be loaded as dependencies.

Not sure what you mean here though? Can you explain this a bit more in detail perhaps?

**Comment by TrySound** [comment]
I meant cdn libs or copying directly in project folder.

**Comment by TrySound** [comment]
Also add rAF to bower, please.

**Comment by anselmh** [comment]
Thanks so far for your suggestions. It seems the polyfill is indeed a bit faster now again. I’ll see if I can make the dependency stuff a bit less messy.

**Comment by TrySound** [comment]
@anselmh Are you sure you need el.closest, not el.matches? closest polyfills both.

**Comment by TrySound** [comment]
And rAF is not devDep

**Comment by TrySound** [comment]
Closest is not devDependency too.

**Comment by TrySound** [comment]
Nice! I asked Jonathan Neal to publish closest on npm.

**Comment by TrySound** [comment]
@anselmh  Closest added to npm
https://www.npmjs.com/package/element-closest

**Comment by TrySound** [comment]
> @anselmh Are you sure you need el.closest instead of el.matches? closest polyfills both.

**Comment by anselmh** [comment]
Thanks. Fixed to use the npm version now. Therefore closing this issue for now.

> @anselmh Are you sure you need el.closest instead of el.matches? closest polyfills both.

I tested this and it didn’t fail while speeding up the polyfill. That’s why. If there’s any issue with it it’s easy to roll back.

**Comment by TrySound** [comment]
@anselmh It works. But el.closest do some more work. It checks current or finds closest parent element with this selector. Better use el.matches.

**Comment by TrySound** [comment]
@anselmh Prefomance, heh))
