### ISSUE TITLE
IE9 not working

### ISSUE THREAD

**Issue by djmtype** [anselmh/object-fit#35]
First, I tried the polyfill on my site. In IE9, it wasn't displaying as intended. So, I took your example and tried it.
[https://github.com/anselmh/object-fit/blob/master/tests/index-cover.html](https://github.com/anselmh/object-fit/blob/master/tests/index-cover.html)

In IE9, it's not working. No errors on the page. Native browsers that support `object-fit` applied to `<img>` display just fine.

**Comment by anselmh** [comment]
This is probably a duplicate to #38.
