### ISSUE TITLE
Warn developers about usage

### ISSUE THREAD

**Issue by sgb-io** [anselmh/object-fit#47]
You should consider adding a warning to the readme about using this polyfill.

It has 677 stars but you've stated in #46 that you are no longer actively developing it. Plus, there is no support for Microsoft Edge (#45), and some quite serious problems (#38, #23) that suggest it is slightly broken.

Some might miss this info and dive into it - best for them and for this project to be up front about it's state.

**Comment by anselmh** [comment]
True, I should really do that. Hopefully I find some time to do this later on today.

**Comment by sgb-io** [comment]
Thanks! For the record, it could still be useful for patching IE :)

**Comment by anselmh** [comment]
If you have any(!!!) idea how to do that, please let me know or come up with a PR. I’d be super happy if we could get it working in IE/Edge again.
