### ISSUE TITLE
Alternative fallback

### ISSUE THREAD

**Issue by mediaformat** [anselmh/object-fit#49]
@primozcigler has developped a viable fallback for IE and Edge see here : 
https://medium.com/@primozcigler/neat-trick-for-css-object-fit-fallback-on-edge-and-other-browsers-afbc53bbb2c3

**Comment by anselmh** [comment]
Yes, I’ve seen this already, thanks. I’m going to add this as a note into the Readme. But please not this provides only the basic feature of object-fit, and behaves a bit differently so always test if it’s working the way you want it to. :)

**Comment by anselmh** [comment]
[Added to README here](https://github.com/anselmh/object-fit/blob/master/README.md#a-viable-alternative-for-edge).

**Comment by primozcigler** [comment]
@mediaformat thank you!

As @anselmh mentioned, my fallback explained in article only supports subset of what is possible to achieve with `object-fit`. But AFAIK the most common use case :smile:

**Comment by anselmh** [comment]
> But AFAIK the most common use case :smile:

It is, so thanks again for building, documenting and publishing this lightweight alternative, @primozcigler! :)

**Comment by mediaformat** [comment]
>This provides only the basic feature of object-fit
@anselmh True, I was thinking narrowly of my use case! Thanks for adding the note!

@primozcigler Thank you sir for the clever fallback!
