### ISSUE TITLE
Document CSSOM CORS: "SecurityError: The operation is insecure." with ext. CSS

### ISSUE THREAD

**Issue by anselmh** [anselmh/object-fit#7]
When using external CSS (like a CDNed CSS, ext. Webfonts) Firefox throws an error in part of our script: 
resp. https://gist.github.com/ydaniv/3033012/#file-mozgetmatchedcssrules-js-L23

There are some hints for this here: http://stackoverflow.com/a/5323868 and http://stackoverflow.com/questions/3211536/accessing-cross-domain-stylesheet-with-cssrules.

The issue, solution and [circumvention hack](https://github.com/rodneyrehm/viewport-units-buggyfill/commit/e1865ca00d20492ba1f75a6ced384a8dae245802) should be well documented so authors don't run into it not knowing what is going on.

**Comment by luruke** [comment]
I had a similar problem like @lolmaus (I was using typekit)

I solved adding this code inside getSheetRules():
```javascript
if (stylesheet.href && stylesheet.href.match(/typekit/)) {
            return [];
}
```
