### ISSUE TITLE
Min-/max- properties not applied

### ISSUE THREAD

**Issue by joeyhoer** [anselmh/object-fit#9]
One of the benefits of `object-fit` is the ability to apply a `min-/max-` `height/width` to an object and have the object fit the constrained dimensions. This works in browsers that natively support `object-fit`, but it does not work with the polyfill.

Initially I thought it might be related to https://github.com/anselmh/object-fit/blob/master/src/polyfill.object-fit.core.js#L54-L60. However that does not seem to be the case.

**Comment by anselmh** [comment]
I’m closing this now. Don’t see an easy solution for it and bloating it up even more is no option for the sake of performance. Sorry.
